services:
  db:
    image: postgres:latest
    env_file: config/.env
    ports:
      - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker/dev/api/Dockerfile
    command: bash ./run_dev.sh
    env_file: config/.env
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/backend/"
      - uploads:/uploads
    depends_on:
      db:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    restart: always

  migrations:
    build:
      context: .
      dockerfile: docker/dev/api/Dockerfile
    command: python3 alembic_upgrade_head.py
    env_file: config/.env
    volumes:
      - "./backend:/backend/"
    depends_on:
      - db

  redis:
    image: redis
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  pgdata:
  uploads:
