"""fix_smallint_pk_types

Revision ID: 0002
Revises: 0001
Create Date: 2024-12-21 13:14:30.068824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('context_types', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.SMALLINT(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('context_types_id_seq'::regclass)"))
    op.alter_column('event_types', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.SMALLINT(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('event_types_id_seq'::regclass)"))
    op.alter_column('permissions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.SMALLINT(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('permissions_id_seq'::regclass)"))
    op.alter_column('project_types', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.SMALLINT(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('task_link_types', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.SMALLINT(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('task_link_types_id_seq'::regclass)"))
    op.alter_column('timezones', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.SMALLINT(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('timezones_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timezones', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('timezones_id_seq'::regclass)"))
    op.alter_column('task_link_types', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('task_link_types_id_seq'::regclass)"))
    op.alter_column('project_types', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('permissions', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('permissions_id_seq'::regclass)"))
    op.alter_column('event_types', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('event_types_id_seq'::regclass)"))
    op.alter_column('context_types', 'id',
               existing_type=sa.SMALLINT(),
               type_=sa.INTEGER(),
               existing_comment='Идентификатор',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('context_types_id_seq'::regclass)"))
    # ### end Alembic commands ###
