"""add_email_comfirm_field_to_user_model

Revision ID: 0003
Revises: 0002
Create Date: 2024-12-28 13:31:42.837450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email_confirm", sa.Boolean(), server_default="false", nullable=False, comment="Email подтвержден"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_confirm")
    # ### end Alembic commands ###
