"""add_references_project_to_chat

Revision ID: 0004
Revises: 0003
Create Date: 2025-04-11 08:17:17.512087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('project_id', sa.Uuid(), nullable=True, comment='Идентификатор проекта'))
    op.alter_column('channels', 'channel_group_id',
               existing_type=sa.UUID(),
               nullable=True,
               existing_comment='Идентификатор группы каналов')
    op.create_foreign_key(None, 'channels', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.alter_column('channels', 'channel_group_id',
               existing_type=sa.UUID(),
               nullable=False,
               existing_comment='Идентификатор группы каналов')
    op.drop_column('channels', 'project_id')
    # ### end Alembic commands ###
